# Generated by Django 5.0.6 on 2024-06-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Максимум 250 сим.', max_length=250, verbose_name='Категорія'),
        ),
    ]
